<?php
/**
 *NWP Framework For IDE
 *URL:HTTP://WWW.NWPIR.COM
 *By:ALIREZA GHADIMI
 *Prg.:PHP Storm V.7.1.3
 */
function e($Pro){}
function html($Pro){}
function ehtml(){}
function head($Pro){}
function ehead(){}
function body($Pro){}
function ebody(){}
function base($Pro){}
function externallink($Pro){}
function meta($Pro){}
function title($Pro){}
function etitle(){}
function style($Pro){}
function estyle(){}
function script($Pro){}
function escript(){}
function a($Pro){}
function ea(){}
function abbr($Pro){}
function eabbr(){}
function address($Pro){}
function eaddress(){}
function area($Pro){}
function b($Pro){}
function eb(){}
function br(){}
function button($Pro){}
function ebutton(){}
function cite($Pro){}
function ecite(){}
function code($Pro){}
function ecode(){}
function col($Pro){}
function dd($Pro){}
function edd(){}
function del($Pro){}
function edel(){}
function dfn($Pro){}
function edfn(){}
function div($Pro){}
function ediv(){}
function dl($Pro){}
function edl(){}
function dt($Pro){}
function edt(){}
function em($Pro){}
function eem(){}
function fieldset($Pro){}
function efieldset(){}
function form($Pro){}
function eform(){}
function h1($Pro){}
function eh1(){}
function h2($Pro){}
function eh2(){}
function h3($Pro){}
function eh3(){}
function h4($Pro){}
function eh4(){}
function h5($Pro){}
function eh5(){}
function h6($Pro){}
function eh6(){}
function hr($Pro){}
function i($Pro){}
function ei(){}
function iframe($Pro){}
function eiframe(){}
function img($Pro){}
function input($Pro){}
function ins($Pro){}
function kbd($Pro){}
function ekbd(){}
function label($Pro){}
function elabel(){}
function legend($Pro){}
function elegend(){}
function li($Pro){}
function eli(){}
function map($Pro){}
function emap(){}
function menu($Pro){}
function emenu(){}
function noscript($Pro){}
function enoscript(){}
function object($Pro){}
function eobject(){}
function ol($Pro){}
function eol(){}
function optgroup($Pro){}
function eoptgroup(){}
function option($Pro){}
function eoption(){}
function p($Pro){}
function ep(){}
function param($Pro){}
function pre($Pro){}
function epre(){}
function q($Pro){}
function eq(){}
function s($Pro){}
function es(){}
function samp($Pro){}
function esamp(){}
function select($Pro){}
function eselect(){}
function small($Pro){}
function esmall(){}
function span($Pro){}
function espan(){}
function strike($Pro){}
function estrike(){}
function strong($Pro){}
function estrong(){}
function sub($Pro){}
function esub(){}
function sup($Pro){}
function esup(){}
function table($Pro){}
function etable(){}
function tbody($Pro){}
function etbody(){}
function td($Pro){}
function etd(){}
function textarea($Pro){}
function etextarea(){}
function foot($Pro){}
function efoot(){}
function th($Pro){}
function eth(){}
function thead($Pro){}
function ethead(){}
function tr($Pro){}
function etr(){}
function tt($Pro){}
function ett(){}
function u($Pro){}
function ul($Pro){}
function eul(){}